//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commons.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commons.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Lights&gt;
        ///  &lt;Light0&gt;
        ///    &lt;!--&lt;环境光：白光&gt;--&gt;
        ///    &lt;position&gt;0,0,0,1&lt;/position&gt;
        ///    &lt;ambient&gt;255,255,255,255&lt;/ambient&gt;
        ///    &lt;diffuse&gt;0,0,0,0&lt;/diffuse&gt;
        ///    &lt;specular&gt;0,0,0,0&lt;/specular&gt;
        ///  &lt;/Light0&gt;
        ///
        ///  &lt;Light1&gt;
        ///    &lt;!--&lt;散射光：Z高处的红光&gt;--&gt;
        ///    &lt;position&gt;0,0,200,1&lt;/position&gt;
        ///    &lt;ambient&gt;0,0,0,0&lt;/ambient&gt;
        ///    &lt;diffuse&gt;255,0,0,255&lt;/diffuse&gt;
        ///    &lt;specular&gt;0,0,0,0&lt;/specular&gt;
        ///  &lt;/Light1&gt;
        ///
        ///  &lt;Light2&gt;
        ///    &lt;!--&lt;高亮光：X高处的绿光&gt;--&gt;
        ///    &lt;position&gt;200,0,0,1&lt;/position&gt;
        ///    &lt;ambient&gt;0,0,0,0&lt;/ambient&gt;
        ///    &lt;diffuse&gt;0,255, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ConfigLight {
            get {
                return ResourceManager.GetString("ConfigLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Materials&gt;
        ///  &lt;CommonBox&gt;
        ///    &lt;ambient&gt;64,64,255,255&lt;/ambient&gt;
        ///    &lt;diffuse&gt;64,64,255,255&lt;/diffuse&gt;
        ///    &lt;specular&gt;64,64,255,255&lt;/specular&gt;
        ///    &lt;emission&gt;0,0,0,0&lt;/emission&gt;
        ///    &lt;shininess&gt;30&lt;/shininess&gt;
        ///  &lt;/CommonBox&gt;
        ///  &lt;ActiveBox&gt;
        ///    &lt;ambient&gt;255,125,125,255&lt;/ambient&gt;
        ///    &lt;diffuse&gt;255,125,125,255&lt;/diffuse&gt;
        ///    &lt;specular&gt;255,255,255,255&lt;/specular&gt;
        ///    &lt;emission&gt;0,0,0,0&lt;/emission&gt;
        ///    &lt;shininess&gt;30&lt;/shininess&gt;
        ///  &lt;/ActiveBox&gt;
        ///  &lt;BoundingBox&gt;
        ///    &lt;ambient&gt;255,255,0,255&lt;/ambient&gt;
        ///    &lt;diffuse&gt;0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ConfigMaterial {
            get {
                return ResourceManager.GetString("ConfigMaterial", resourceCulture);
            }
        }
    }
}
